package com.example.devDemo.consts;

public class JsonConst {



    public static final String jsonString = "{\n" +
            "        \"id\": \"0024DFDB00824D7F9C11D2791EDCEF68\",\n" +
            "        \"task_code\": \"T03BEJ22033110300001000\",\n" +
            "        \"task_status\": \"TEMP\",\n" +
            "        \"task_type\": \"AXX\",\n" +
            "        \"task_type_status\": \"WP\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": null,\n" +
            "        \"store_code\": null,\n" +
            "        \"applicant_name\": \"杨蕃源\",\n" +
            "        \"applicant\": \"oWvDz0NNKp3qVZykn_Q96KdzRQkA-注销\",\n" +
            "        \"apply_time\": 1676969600000,\n" +
            "        \"apply_phone_no\": \"15116373905\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": \"b00001_che\",\n" +
            "        \"type_name\": \"车辆信息变更\",\n" +
            "        \"handler_code\": null,\n" +
            "        \"handler_name\": null,\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"1010100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1648693841000,\n" +
            "        \"create_by\": \"杨蕃源\",\n" +
            "        \"update_time\": null,\n" +
            "        \"update_by\": null,\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"3\",\n" +
            "        \"weight_score\": \"00\",\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"ABEJ090Y2022B000169N,ABEJ090CTP22B000291P\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": null,\n" +
            "        \"plate_no\": \"LSYH78TG\",\n" +
            "        \"start_time\": null,\n" +
            "        \"end_time\": null,\n" +
            "        \"task_sign\": null,\n" +
            "        \"back_url\": null,\n" +
            "        \"task_tab\": null,\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"北京分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"1\",\n" +
            "        \"business_audit_type\": null,\n" +
            "        \"push_type\": null,\n" +
            "        \"system_source\": \"29\",\n" +
            "        \"is_sign_ca\": null,\n" +
            "        \"old_task_code\": null,\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": null,\n" +
            "        \"task_org_code\": null,\n" +
            "        \"task_org_name\": null,\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": null,\n" +
            "        \"handler_group_name\": null,\n" +
            "        \"senior_order_type_code\": null,\n" +
            "        \"senior_order_type_name\": null,\n" +
            "        \"senior_order_child_type_code\": null,\n" +
            "        \"senior_order_child_type_name\": null,\n" +
            "        \"detailed_type_code\": null,\n" +
            "        \"detailed_type_name\": null,\n" +
            "        \"customer_no\": null,\n" +
            "        \"senior_order_no\": null,\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": null,\n" +
            "        \"site_code\": null,\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": \"0035484279514841A08A0DF3AA70EE70\",\n" +
            "        \"task_code\": \"T12GUZ23081516220001000\",\n" +
            "        \"task_status\": \"SB\",\n" +
            "        \"task_type\": \"BGF\",\n" +
            "        \"task_type_status\": \"SB\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": null,\n" +
            "        \"store_code\": null,\n" +
            "        \"applicant_name\": \"范欢庆\",\n" +
            "        \"applicant\": null,\n" +
            "        \"apply_time\": 1692087759000,\n" +
            "        \"apply_phone_no\": \"17601365725\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": null,\n" +
            "        \"type_name\": null,\n" +
            "        \"handler_code\": \"080330\",\n" +
            "        \"handler_name\": \"丘碧霞\",\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"5010100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1692087759000,\n" +
            "        \"create_by\": \"刘星星\",\n" +
            "        \"update_time\": 1692087856000,\n" +
            "        \"update_by\": \"丘碧霞\",\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"11\",\n" +
            "        \"weight_score\": null,\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"AGUZ00E17A22QAAAAA6C\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": \"转正式\",\n" +
            "        \"plate_no\": \"\",\n" +
            "        \"start_time\": 1692087810000,\n" +
            "        \"end_time\": 1692087856000,\n" +
            "        \"task_sign\": \"11\",\n" +
            "        \"back_url\": null,\n" +
            "        \"task_tab\": null,\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"广东分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"0\",\n" +
            "        \"business_audit_type\": null,\n" +
            "        \"push_type\": null,\n" +
            "        \"system_source\": null,\n" +
            "        \"is_sign_ca\": null,\n" +
            "        \"old_task_code\": null,\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": \"P17\",\n" +
            "        \"task_org_code\": \"440100\",\n" +
            "        \"task_org_name\": \"广东分公司广州分公司\",\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": \"8c00075830b20ae6e54bf16939508189\",\n" +
            "        \"handler_group_name\": \"广东广州不规则报案组\",\n" +
            "        \"senior_order_type_code\": \"000A\",\n" +
            "        \"senior_order_type_name\": \"特色服务\",\n" +
            "        \"senior_order_child_type_code\": \"000A001\",\n" +
            "        \"senior_order_child_type_name\": \"不规则报案\",\n" +
            "        \"detailed_type_code\": \"3\",\n" +
            "        \"detailed_type_name\": \"保单信息不符\",\n" +
            "        \"customer_no\": \"P17GUZ2308151622000001\",\n" +
            "        \"senior_order_no\": \"4541588\",\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": null,\n" +
            "        \"site_code\": null,\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": \"0042B9FC5B6A4FB2A5CC9A7D2F0C7286\",\n" +
            "        \"task_code\": \"T03SHH24050910120002000\",\n" +
            "        \"task_status\": \"DS\",\n" +
            "        \"task_type\": \"AXX\",\n" +
            "        \"task_type_status\": \"PB\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": \"上海sy测试门店\",\n" +
            "        \"store_code\": \"ST2000001426741187\",\n" +
            "        \"applicant_name\": \"5\",\n" +
            "        \"applicant\": null,\n" +
            "        \"apply_time\": 1715220770000,\n" +
            "        \"apply_phone_no\": \"5\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": \"b00001_others\",\n" +
            "        \"type_name\": \"其他批改\",\n" +
            "        \"handler_code\": \"3420\",\n" +
            "        \"handler_name\": \"许晟\",\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"3010100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1715220770000,\n" +
            "        \"create_by\": null,\n" +
            "        \"update_time\": 1715240399000,\n" +
            "        \"update_by\": null,\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"3\",\n" +
            "        \"weight_score\": null,\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"ASHH011Y2024B000155U\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": null,\n" +
            "        \"plate_no\": \"LSD73D6\",\n" +
            "        \"start_time\": 1715240390000,\n" +
            "        \"end_time\": 1715240399000,\n" +
            "        \"task_sign\": null,\n" +
            "        \"back_url\": null,\n" +
            "        \"task_tab\": \"23\",\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"上海分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"0\",\n" +
            "        \"business_audit_type\": null,\n" +
            "        \"push_type\": null,\n" +
            "        \"system_source\": null,\n" +
            "        \"is_sign_ca\": \"0\",\n" +
            "        \"old_task_code\": \"T04SHH24050910120001000\",\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": \"YMD\",\n" +
            "        \"task_org_code\": null,\n" +
            "        \"task_org_name\": null,\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": null,\n" +
            "        \"handler_group_name\": null,\n" +
            "        \"senior_order_type_code\": \"000B\",\n" +
            "        \"senior_order_type_name\": \"保单服务\",\n" +
            "        \"senior_order_child_type_code\": \"GXX\",\n" +
            "        \"senior_order_child_type_name\": \"改信息\",\n" +
            "        \"detailed_type_code\": \"XSRG\",\n" +
            "        \"detailed_type_name\": \"线上人工\",\n" +
            "        \"customer_no\": \"YMD03SHH24050910120002000\",\n" +
            "        \"senior_order_no\": \"S00SHH24050910120002000\",\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": \"CXTPH\",\n" +
            "        \"site_code\": \"tjr\",\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": \"0047167FA659409BA9FD7040C240361C\",\n" +
            "        \"task_code\": \"T04GUZ23072610040001000\",\n" +
            "        \"task_status\": \"JX\",\n" +
            "        \"task_type\": \"CHEBIAN\",\n" +
            "        \"task_type_status\": \"JX\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": null,\n" +
            "        \"store_code\": null,\n" +
            "        \"applicant_name\": \"沙悦\",\n" +
            "        \"applicant\": \"oWvDz0BZ3BetOmsuM0412qOkmfME-注销\",\n" +
            "        \"apply_time\": 1690337064000,\n" +
            "        \"apply_phone_no\": \"13166025850\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": \"b00001_guh\",\n" +
            "        \"type_name\": \"过户批改\",\n" +
            "        \"handler_code\": \"YYG\",\n" +
            "        \"handler_name\": \"云易改\",\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"5010100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1690337064000,\n" +
            "        \"create_by\": \"沙悦\",\n" +
            "        \"update_time\": null,\n" +
            "        \"update_by\": null,\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"3\",\n" +
            "        \"weight_score\": \"00\",\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"AGUZ000CTP23B000495I\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": null,\n" +
            "        \"plate_no\": \"粤C666666\",\n" +
            "        \"start_time\": 1690337065000,\n" +
            "        \"end_time\": 1690337064000,\n" +
            "        \"task_sign\": null,\n" +
            "        \"back_url\": \"https://mcarsit-sit.cpic.com.cn/mcar/correct.html?authentication=true&unionId=o4IwmwPKK3r3eZikrWtw_KvBZrzM&openId=oWvDz0BZ3BetOmsuM0412qOkmfME&applicantName=沙悦&applicantIdNum=rLHi+ZCMZHcPrJQA0EU+450c2NWcZ3biJKDztKKcVQs=&branchCode=5010100&branchName广东分公司&businessEntrance=ymd&encodingByAESFalg=1#/policychoice\",\n" +
            "        \"task_tab\": \"66\",\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"广东分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"0\",\n" +
            "        \"business_audit_type\": \"1\",\n" +
            "        \"push_type\": \"1\",\n" +
            "        \"system_source\": null,\n" +
            "        \"is_sign_ca\": null,\n" +
            "        \"old_task_code\": null,\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": \"YMD\",\n" +
            "        \"task_org_code\": null,\n" +
            "        \"task_org_name\": null,\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": null,\n" +
            "        \"handler_group_name\": null,\n" +
            "        \"senior_order_type_code\": \"000B\",\n" +
            "        \"senior_order_type_name\": \"保单服务\",\n" +
            "        \"senior_order_child_type_code\": \"GXX\",\n" +
            "        \"senior_order_child_type_name\": \"改信息\",\n" +
            "        \"detailed_type_code\": \"XSRG\",\n" +
            "        \"detailed_type_name\": \"线上人工\",\n" +
            "        \"customer_no\": \"YMD04GUZ23072610040001000\",\n" +
            "        \"senior_order_no\": \"S00GUZ23072610040001000\",\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": null,\n" +
            "        \"site_code\": null,\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": \"00491BB068494B379F9CBB2E37B6B7AE\",\n" +
            "        \"task_code\": \"T03NAJ21102215440003000\",\n" +
            "        \"task_status\": \"TEMP\",\n" +
            "        \"task_type\": \"AXX\",\n" +
            "        \"task_type_status\": \"WP\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": null,\n" +
            "        \"store_code\": null,\n" +
            "        \"applicant_name\": \"周理\",\n" +
            "        \"applicant\": \"oWvDz0DF808IrBd738cB6AGktM8c-注销\",\n" +
            "        \"apply_time\": 1676969600000,\n" +
            "        \"apply_phone_no\": \"17602158888\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": \"b00001_syx_cxtb\",\n" +
            "        \"type_name\": \"商业险退保\",\n" +
            "        \"handler_code\": null,\n" +
            "        \"handler_name\": null,\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"3020100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1634888692000,\n" +
            "        \"create_by\": null,\n" +
            "        \"update_time\": null,\n" +
            "        \"update_by\": null,\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"3\",\n" +
            "        \"weight_score\": \"00\",\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"ANAJA99Y2021B000781R\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": null,\n" +
            "        \"plate_no\": \"苏A16389\",\n" +
            "        \"start_time\": null,\n" +
            "        \"end_time\": null,\n" +
            "        \"task_sign\": null,\n" +
            "        \"back_url\": null,\n" +
            "        \"task_tab\": \"77\",\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"江苏分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"0\",\n" +
            "        \"business_audit_type\": null,\n" +
            "        \"push_type\": null,\n" +
            "        \"system_source\": null,\n" +
            "        \"is_sign_ca\": null,\n" +
            "        \"old_task_code\": null,\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": null,\n" +
            "        \"task_org_code\": null,\n" +
            "        \"task_org_name\": null,\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": null,\n" +
            "        \"handler_group_name\": null,\n" +
            "        \"senior_order_type_code\": null,\n" +
            "        \"senior_order_type_name\": null,\n" +
            "        \"senior_order_child_type_code\": null,\n" +
            "        \"senior_order_child_type_name\": null,\n" +
            "        \"detailed_type_code\": null,\n" +
            "        \"detailed_type_name\": null,\n" +
            "        \"customer_no\": null,\n" +
            "        \"senior_order_no\": null,\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": null,\n" +
            "        \"site_code\": null,\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": \"0059B03426DF4AE98DD7CA6169209A56\",\n" +
            "        \"task_code\": \"T11GUZ23081014170001000\",\n" +
            "        \"task_status\": \"SB\",\n" +
            "        \"task_type\": \"GJ\",\n" +
            "        \"task_type_status\": \"SB\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": null,\n" +
            "        \"store_code\": null,\n" +
            "        \"applicant_name\": \"阿松大\",\n" +
            "        \"applicant\": null,\n" +
            "        \"apply_time\": 1691648247000,\n" +
            "        \"apply_phone_no\": \"11111111111\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": null,\n" +
            "        \"type_name\": null,\n" +
            "        \"handler_code\": \"DG5212\",\n" +
            "        \"handler_name\": \"何倩芸\",\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"5010100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1691648247000,\n" +
            "        \"create_by\": \"黄芳\",\n" +
            "        \"update_time\": 1691648271000,\n" +
            "        \"update_by\": \"何倩芸\",\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"11\",\n" +
            "        \"weight_score\": null,\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"AGUZ000Y2022B000659I\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": \"111\",\n" +
            "        \"plate_no\": \"桂A78978\",\n" +
            "        \"start_time\": 1691648265000,\n" +
            "        \"end_time\": 1691648271000,\n" +
            "        \"task_sign\": \"11\",\n" +
            "        \"back_url\": null,\n" +
            "        \"task_tab\": null,\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"广东分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"0\",\n" +
            "        \"business_audit_type\": null,\n" +
            "        \"push_type\": null,\n" +
            "        \"system_source\": null,\n" +
            "        \"is_sign_ca\": null,\n" +
            "        \"old_task_code\": null,\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": \"P17\",\n" +
            "        \"task_org_code\": \"440000\",\n" +
            "        \"task_org_name\": \"广东分公司广东分公司本部\",\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": \"c2563dfe5a1d74e87e7becd0ca073486\",\n" +
            "        \"handler_group_name\": \"本部其他\",\n" +
            "        \"senior_order_type_code\": \"0002\",\n" +
            "        \"senior_order_type_name\": \"理赔服务\",\n" +
            "        \"senior_order_child_type_code\": \"0002001\",\n" +
            "        \"senior_order_child_type_name\": \"查勘服务\",\n" +
            "        \"detailed_type_code\": \"0002001003\",\n" +
            "        \"detailed_type_name\": \"定损价格争议\",\n" +
            "        \"customer_no\": \"P17GUZ2308101417000001\",\n" +
            "        \"senior_order_no\": \"Q28202308101764249\",\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": null,\n" +
            "        \"site_code\": null,\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": \"006F7B2E371D4E7BB878ABF09AD9D393\",\n" +
            "        \"task_code\": \"T12GUZ23091910340001000\",\n" +
            "        \"task_status\": \"SB\",\n" +
            "        \"task_type\": \"BGF\",\n" +
            "        \"task_type_status\": \"SB\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": null,\n" +
            "        \"store_code\": null,\n" +
            "        \"applicant_name\": \"43\",\n" +
            "        \"applicant\": null,\n" +
            "        \"apply_time\": 1695090858000,\n" +
            "        \"apply_phone_no\": \"15036171065\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": null,\n" +
            "        \"type_name\": null,\n" +
            "        \"handler_code\": \"060004\",\n" +
            "        \"handler_name\": \"唐春梅\",\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"5010100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1695090858000,\n" +
            "        \"create_by\": \"赵巧美\",\n" +
            "        \"update_time\": 1695091085000,\n" +
            "        \"update_by\": \"唐春梅\",\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"11\",\n" +
            "        \"weight_score\": null,\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": \"111\",\n" +
            "        \"plate_no\": \"\",\n" +
            "        \"start_time\": 1695091069000,\n" +
            "        \"end_time\": 1695091085000,\n" +
            "        \"task_sign\": \"11\",\n" +
            "        \"back_url\": null,\n" +
            "        \"task_tab\": null,\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"广东分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"0\",\n" +
            "        \"business_audit_type\": null,\n" +
            "        \"push_type\": null,\n" +
            "        \"system_source\": null,\n" +
            "        \"is_sign_ca\": null,\n" +
            "        \"old_task_code\": null,\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": \"P17\",\n" +
            "        \"task_org_code\": \"440100\",\n" +
            "        \"task_org_name\": \"广东分公司广州分公司\",\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": \"3cb63f6d24c47e8ee0f70a97c3db7f70\",\n" +
            "        \"handler_group_name\": \"广东分公司广州分公司组\",\n" +
            "        \"senior_order_type_code\": \"000A\",\n" +
            "        \"senior_order_type_name\": \"特色服务\",\n" +
            "        \"senior_order_child_type_code\": \"000A001\",\n" +
            "        \"senior_order_child_type_name\": \"不规则报案\",\n" +
            "        \"detailed_type_code\": \"3\",\n" +
            "        \"detailed_type_name\": \"保单信息不符\",\n" +
            "        \"customer_no\": \"P17GUZ2309191034000001\",\n" +
            "        \"senior_order_no\": \"4553755\",\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": null,\n" +
            "        \"site_code\": null,\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": \"007CF2A57FFB4530B9B4F81879C54BEB\",\n" +
            "        \"task_code\": \"T12GUZ23101914190001000\",\n" +
            "        \"task_status\": \"SB\",\n" +
            "        \"task_type\": \"BGF\",\n" +
            "        \"task_type_status\": \"SB\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": null,\n" +
            "        \"store_code\": null,\n" +
            "        \"applicant_name\": \"张思思\",\n" +
            "        \"applicant\": null,\n" +
            "        \"apply_time\": 1697696369000,\n" +
            "        \"apply_phone_no\": \"11111111111\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": null,\n" +
            "        \"type_name\": null,\n" +
            "        \"handler_code\": \"060004\",\n" +
            "        \"handler_name\": \"唐春梅\",\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"5010100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1697696369000,\n" +
            "        \"create_by\": \"黄芳\",\n" +
            "        \"update_time\": 1697696603000,\n" +
            "        \"update_by\": \"唐春梅\",\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"11\",\n" +
            "        \"weight_score\": null,\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": \"222\",\n" +
            "        \"plate_no\": \"\",\n" +
            "        \"start_time\": 1697696593000,\n" +
            "        \"end_time\": 1697696603000,\n" +
            "        \"task_sign\": \"11\",\n" +
            "        \"back_url\": null,\n" +
            "        \"task_tab\": null,\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"广东分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"0\",\n" +
            "        \"business_audit_type\": null,\n" +
            "        \"push_type\": null,\n" +
            "        \"system_source\": null,\n" +
            "        \"is_sign_ca\": null,\n" +
            "        \"old_task_code\": null,\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": \"P17\",\n" +
            "        \"task_org_code\": \"440100\",\n" +
            "        \"task_org_name\": \"广东分公司广州分公司\",\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": \"3cb63f6d24c47e8ee0f70a97c3db7f70\",\n" +
            "        \"handler_group_name\": \"广东分公司广州分公司组\",\n" +
            "        \"senior_order_type_code\": \"000A\",\n" +
            "        \"senior_order_type_name\": \"特色服务\",\n" +
            "        \"senior_order_child_type_code\": \"000A001\",\n" +
            "        \"senior_order_child_type_name\": \"不规则报案\",\n" +
            "        \"detailed_type_code\": \"1\",\n" +
            "        \"detailed_type_name\": \"超时报立案\",\n" +
            "        \"customer_no\": \"P17GUZ2310191419000001\",\n" +
            "        \"senior_order_no\": \"4553950\",\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": null,\n" +
            "        \"site_code\": null,\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": \"008C8104D371417DB21D26DE080A7BC2\",\n" +
            "        \"task_code\": \"T12JIN23103113300002000\",\n" +
            "        \"task_status\": \"WP\",\n" +
            "        \"task_type\": \"BGC\",\n" +
            "        \"task_type_status\": \"WP\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": null,\n" +
            "        \"store_code\": null,\n" +
            "        \"applicant_name\": \"不规则测试2\",\n" +
            "        \"applicant\": null,\n" +
            "        \"apply_time\": 1698730249000,\n" +
            "        \"apply_phone_no\": \"12222222222\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": null,\n" +
            "        \"type_name\": null,\n" +
            "        \"handler_code\": \"#06009\",\n" +
            "        \"handler_name\": \"周勇良\",\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"3090100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1698730249000,\n" +
            "        \"create_by\": \"李乐\",\n" +
            "        \"update_time\": 1698730250000,\n" +
            "        \"update_by\": null,\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"11\",\n" +
            "        \"weight_score\": null,\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"QQQQQ\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": null,\n" +
            "        \"plate_no\": \"QQQQQ\",\n" +
            "        \"start_time\": 1698730250000,\n" +
            "        \"end_time\": null,\n" +
            "        \"task_sign\": \"91\",\n" +
            "        \"back_url\": null,\n" +
            "        \"task_tab\": null,\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"山东分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"0\",\n" +
            "        \"business_audit_type\": null,\n" +
            "        \"push_type\": null,\n" +
            "        \"system_source\": null,\n" +
            "        \"is_sign_ca\": null,\n" +
            "        \"old_task_code\": null,\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": \"P17\",\n" +
            "        \"task_org_code\": \"370000\",\n" +
            "        \"task_org_name\": \"山东分公司山东分公司本部\",\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": \"7de928e543677b4f54c9aef7ad21299a\",\n" +
            "        \"handler_group_name\": \"山东分公司兜底组\",\n" +
            "        \"senior_order_type_code\": \"000A\",\n" +
            "        \"senior_order_type_name\": \"特色服务\",\n" +
            "        \"senior_order_child_type_code\": \"000A001\",\n" +
            "        \"senior_order_child_type_name\": \"不规则报案\",\n" +
            "        \"detailed_type_code\": \"1\",\n" +
            "        \"detailed_type_name\": \"超时报立案\",\n" +
            "        \"customer_no\": \"P17JIN2310311330000002\",\n" +
            "        \"senior_order_no\": \"4553996\",\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": null,\n" +
            "        \"site_code\": null,\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": \"0092B80999E64BAC9D88FCA8C860855C\",\n" +
            "        \"task_code\": \"T11GUZ23091417020001000\",\n" +
            "        \"task_status\": \"WP\",\n" +
            "        \"task_type\": \"GJ\",\n" +
            "        \"task_type_status\": \"WP\",\n" +
            "        \"queue_number\": null,\n" +
            "        \"store_name\": null,\n" +
            "        \"store_code\": null,\n" +
            "        \"applicant_name\": \"何倩云\",\n" +
            "        \"applicant\": null,\n" +
            "        \"apply_time\": 1694682162000,\n" +
            "        \"apply_phone_no\": \"13524722726\",\n" +
            "        \"booking_time\": null,\n" +
            "        \"type_code\": null,\n" +
            "        \"type_name\": null,\n" +
            "        \"handler_code\": \"#05019\",\n" +
            "        \"handler_name\": \"宁宁\",\n" +
            "        \"remark\": null,\n" +
            "        \"branch_code\": \"5010100\",\n" +
            "        \"address\": null,\n" +
            "        \"time_Area_id\": null,\n" +
            "        \"create_time\": 1694682162000,\n" +
            "        \"create_by\": \"杜文慧\",\n" +
            "        \"update_time\": 1694682163000,\n" +
            "        \"update_by\": null,\n" +
            "        \"del_flag\": \"1\",\n" +
            "        \"task_in\": \"11\",\n" +
            "        \"weight_score\": null,\n" +
            "        \"result_type\": null,\n" +
            "        \"applicant_gender\": null,\n" +
            "        \"policy_no\": \"\",\n" +
            "        \"tracking_number\": null,\n" +
            "        \"reissue_remark\": null,\n" +
            "        \"plate_no\": \"\",\n" +
            "        \"start_time\": 1694682163000,\n" +
            "        \"end_time\": null,\n" +
            "        \"task_sign\": \"91\",\n" +
            "        \"back_url\": null,\n" +
            "        \"task_tab\": null,\n" +
            "        \"task_system_tab\": null,\n" +
            "        \"branch_name\": \"广东分公司\",\n" +
            "        \"create_reason\": null,\n" +
            "        \"is_user_vip\": \"0\",\n" +
            "        \"business_audit_type\": null,\n" +
            "        \"push_type\": null,\n" +
            "        \"system_source\": null,\n" +
            "        \"is_sign_ca\": null,\n" +
            "        \"old_task_code\": null,\n" +
            "        \"task_flag\": \"0\",\n" +
            "        \"uid\": null,\n" +
            "        \"system_source_ident\": \"P17\",\n" +
            "        \"task_org_code\": \"445300\",\n" +
            "        \"task_org_name\": \"广东分公司云浮中心支公司\",\n" +
            "        \"task_dept_code\": null,\n" +
            "        \"task_dept_name\": null,\n" +
            "        \"handler_group_id\": \"c7fe195269c50f38e376cbf03cb55575\",\n" +
            "        \"handler_group_name\": \"广东分公司组\",\n" +
            "        \"senior_order_type_code\": \"0002\",\n" +
            "        \"senior_order_type_name\": \"理赔服务\",\n" +
            "        \"senior_order_child_type_code\": \"0002003\",\n" +
            "        \"senior_order_child_type_name\": \"赔付情况\",\n" +
            "        \"detailed_type_code\": \"0002003001\",\n" +
            "        \"detailed_type_name\": \"催促赔付时效\",\n" +
            "        \"customer_no\": \"P17GUZ2309141702000001\",\n" +
            "        \"senior_order_no\": \"Q23202309141773370\",\n" +
            "        \"policy_branch_code\": null,\n" +
            "        \"cross_task\": null,\n" +
            "        \"urging_count\": 0,\n" +
            "        \"nature_revert_task_code\": null,\n" +
            "        \"task_nature\": null,\n" +
            "        \"cross_wait\": null,\n" +
            "        \"person_id\": null,\n" +
            "        \"correct_task_source\": null,\n" +
            "        \"site_code\": null,\n" +
            "        \"evaluate_status\": null,\n" +
            "        \"show_evaluate\": null,\n" +
            "        \"unionId\": null\n" +
            "    }";

}
